adminUser:
  password: vault:jx-aps-lordballistic/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-lordballistic:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-lordballistic:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:jx-aps-lordballistic/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:jx-aps-lordballistic/prow:hmacToken
